# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FSCaldrDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FSCaldrDemo
	pod 'FSCalendar'
  pod "BSImagePicker", "~> 2.8"
  pod 'WXWaveView'
  pod 'YXWaveView'
  pod 'iOSPhotoEditor'
  pod 'GPUImage'
  target 'FSCaldrDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FSCaldrDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
